import AppKit

/// Watches the pasteboard for the daemon and writes what the phone sends.
/// macOS has no change notification, so it polls `changeCount`, which is cheap.
final class ClipboardBridge {
    static let maxText = 1024 * 1024
    static let maxImage = 16 * 1024 * 1024

    /// Markers password managers and system tools put on items that shouldn't leave the Mac
    /// (see nspasteboard.org).
    private static let skipped: Set<NSPasteboard.PasteboardType> = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
        .init("com.agilebits.onepassword"),
    ]

    private let daemon: DaemonClient
    private let pasteboard = NSPasteboard.general
    private var lastChange: Int
    private var timer: Timer?
    private let encodeQueue = DispatchQueue(label: "tether.clipboard.encode")
    var enabled = true

    init(daemon: DaemonClient) {
        self.daemon = daemon
        lastChange = pasteboard.changeCount
    }

    func start() {
        let t = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in self?.poll() }
        t.tolerance = 0.2
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    private func poll() {
        let count = pasteboard.changeCount
        guard count != lastChange else { return }
        lastChange = count
        guard enabled, daemon.running else { return }
        let types = Set(pasteboard.types ?? [])
        if !types.isDisjoint(with: Self.skipped) || types.contains(.fileURL) { return }

        if let text = pasteboard.string(forType: .string), !text.isEmpty {
            if text.utf8.count <= Self.maxText {
                daemon.post(["cmd": "clip_local", "text": text])
            }
            return
        }
        let png = pasteboard.data(forType: .png)
        let tiff = png == nil ? pasteboard.data(forType: .tiff) : nil
        guard png != nil || tiff != nil else { return }
        encodeQueue.async { [daemon = self.daemon] in
            guard let data = png ?? tiff.flatMap({ NSBitmapImageRep(data: $0)?.representation(using: .png, properties: [:]) }),
                  data.count <= Self.maxImage else { return }
            daemon.post(["cmd": "clip_local_image", "mime": "image/png", "data": data.base64EncodedString()])
        }
    }

    func set(text: String) {
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
        lastChange = pasteboard.changeCount
    }

    func set(image data: Data, mime: String) {
        let item = NSPasteboardItem()
        if mime == "image/png" {
            item.setData(data, forType: .png)
        } else if let rep = NSBitmapImageRep(data: data), let png = rep.representation(using: .png, properties: [:]) {
            item.setData(png, forType: .png)
        } else {
            return
        }
        // Many Mac apps paste TIFF only.
        if let tiff = NSImage(data: data)?.tiffRepresentation {
            item.setData(tiff, forType: .tiff)
        }
        pasteboard.clearContents()
        pasteboard.writeObjects([item])
        lastChange = pasteboard.changeCount
    }
}
